# Generated by Django 2.1.3 on 2018-11-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do programa')),
                ('horario_exibicao', models.TimeField(verbose_name='Horário de exibição')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Programação')),
                ('programa', models.ManyToManyField(related_name='programas', to='radio.Programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Programação',
                'verbose_name_plural': 'Programações',
            },
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Rádio')),
            ],
            options={
                'verbose_name': 'Rádio',
                'verbose_name_plural': 'Rádios',
            },
        ),
        migrations.AddField(
            model_name='programacao',
            name='radio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Radio', verbose_name='Rádio'),
        ),
    ]
