# Generated by Django 2.1.3 on 2018-11-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radio',
            options={'verbose_name': 'Rádio', 'verbose_name_plural': 'Rádios'},
        ),
    ]
