# Generated by Django 2.1.3 on 2018-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ('categoria', 'horario_exibicao'), 'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.AlterField(
            model_name='programa',
            name='categoria',
            field=models.CharField(choices=[(1, 'Futebol'), (2, 'Musica'), (3, 'Política'), (4, 'Cultura')], max_length=50, verbose_name='Categoria'),
        ),
    ]
