# Generated by Django 2.1.3 on 2018-11-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='categoria',
            field=models.CharField(choices=[('futebol', 'Not relevant'), ('musica', 'Review'), ('politica', 'Maybe relevant'), ('cultural', 'Relevant')], default=1, max_length=50, verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
