# Generated by Django 2.1.3 on 2018-11-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20181107_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Futebol'), (2, 'Musica'), (3, 'Política'), (4, 'Cultura')], max_length=50, verbose_name='Categoria'),
        ),
    ]
