# Generated by Django 2.1.3 on 2018-11-08 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20181108_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='programacao',
        ),
        migrations.RemoveField(
            model_name='programacao',
            name='radio',
        ),
        migrations.AddField(
            model_name='programa',
            name='radio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radio.Radio', verbose_name='Rádio'),
            preserve_default=False,
        ),
    ]
