# Generated by Django 2.1.3 on 2018-11-05 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20181105_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do programa')),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Radio', verbose_name='Rádio')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Programação')),
                ('prgrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Programa', verbose_name='Programa')),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Radio', verbose_name='Rádio')),
            ],
            options={
                'verbose_name': 'Programação',
                'verbose_name_plural': 'Programações',
            },
        ),
    ]
