# Generated by Django 2.1.3 on 2018-11-08 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20181108_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacao',
            name='nome',
        ),
        migrations.AddField(
            model_name='programacao',
            name='programa',
            field=models.ManyToManyField(related_name='programas', to='radio.Programa', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='programacao',
            name='radio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radio.Radio', verbose_name='Rádio'),
            preserve_default=False,
        ),
    ]
