# Generated by Django 2.1.3 on 2018-11-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_auto_20181108_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Futebol'), (2, 'Musica'), (3, 'Política'), (4, 'Cultura')], verbose_name='Categoria'),
        ),
    ]
