# Generated by Django 2.1.3 on 2018-11-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_remove_programa_radio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacao',
            name='prgrama',
        ),
        migrations.AddField(
            model_name='programacao',
            name='programa',
            field=models.ManyToManyField(related_name='programas', to='radio.Programa', verbose_name='Programa'),
        ),
    ]
