# Generated by Django 2.1.3 on 2018-11-08 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_auto_20181108_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exibicao', models.DateTimeField(verbose_name='Data de exibição')),
            ],
        ),
        migrations.CreateModel(
            name='GradeProgramacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_exibicao', models.TimeField(verbose_name='Horário de exibição')),
            ],
            options={
                'verbose_name': 'Programação',
                'verbose_name_plural': 'Programações',
            },
        ),
        migrations.RemoveField(
            model_name='programacao',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='programacao',
            name='radio',
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['categoria'], 'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.RemoveField(
            model_name='programa',
            name='horario_exibicao',
        ),
        migrations.DeleteModel(
            name='Programacao',
        ),
        migrations.AddField(
            model_name='gradeprogramacao',
            name='programa',
            field=models.ManyToManyField(related_name='programas', to='radio.Programa', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='gradeprogramacao',
            name='radio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Radio', verbose_name='Rádio'),
        ),
        migrations.AddField(
            model_name='grade',
            name='programacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.GradeProgramacao', verbose_name='Grade de Programação'),
        ),
    ]
