# Generated by Django 2.1.3 on 2018-11-08 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_auto_20181108_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='programacao',
        ),
        migrations.AddField(
            model_name='gradeprogramacao',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radio.Grade', verbose_name='Grade de Programação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='data_exibicao',
            field=models.DateField(verbose_name='Data de exibição'),
        ),
    ]
