# Generated by Django 2.1.3 on 2018-11-08 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_auto_20181108_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeprogramacao',
            name='programa',
        ),
        migrations.AddField(
            model_name='gradeprogramacao',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='radio.Programa', verbose_name='Programa'),
            preserve_default=False,
        ),
    ]
