# Generated by Django 2.1.3 on 2018-11-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_auto_20181107_1912'),
        ('radio', '0008_auto_20181108_0256'),
    ]

    operations = [
    ]
