# Generated by Django 2.1.3 on 2018-11-10 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0010_auto_20181108_0302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Grade de Programação', 'verbose_name_plural': 'Grades de Programações'},
        ),
        migrations.AlterModelOptions(
            name='gradeprogramacao',
            options={'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.RemoveField(
            model_name='gradeprogramacao',
            name='horario_exibicao',
        ),
        migrations.AddField(
            model_name='gradeprogramacao',
            name='data_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Fim'),
        ),
        migrations.AddField(
            model_name='gradeprogramacao',
            name='data_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Início'),
        ),
        migrations.AlterField(
            model_name='gradeprogramacao',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_programacao', to='radio.Grade', verbose_name='Grade de Programação'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='radio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='radio.Radio', verbose_name='Rádio'),
        ),
    ]
