# Generated by Django 2.1.3 on 2018-11-12 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0012_auto_20181110_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='radio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='radio.Radio', verbose_name='Rádio'),
        ),
    ]
